{{- if .Values.dash.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dash
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.dash.host }}
    http:
      paths:
        backend:
          serviceName: dash
          servicePort: dash-http
{{- end }}